// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Unified button colors for MenuEdit
type ButtonColor string

const (
	BUTTON_RED     ButtonColor = "red"
	BUTTON_GREEN   ButtonColor = "green"
	BUTTON_YELLOW  ButtonColor = "yellow"
	BUTTON_PRIMARY ButtonColor = "primary"
)

// buttonColorClass maps ButtonColor to a CSS class.
// For primary, we support solid (non-hover) and hover variants via the hover flag.
func buttonColorClass(color ButtonColor, hover bool) string {
	switch color {
	case BUTTON_RED:
		return "button_red"
	case BUTTON_GREEN:
		return "button_green"
	case BUTTON_YELLOW:
		return "button_yellow"
	case BUTTON_PRIMARY:
		return "button_primary"
	default:
		return ""
	}
}

type ButtonConfig struct {
	ID        string
	Icon      string
	Name      string
	Type      string
	HxGet     string
	HxPost    string
	HxVals    string
	HxTrigger string
	Class     string
	Color     ButtonColor
	Hover     bool
	HScript   string
	Disabled  bool
}

func MenuEdit(mainButton ButtonConfig, buttonGroups ...[]ButtonConfig) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-w-min select-none\"><div class=\"relative\"><div class=\"w-auto inline-flex justify-end items-stretch rounded-lg p-[0.2rem] background_primary border border_secondary\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = InnerButton(mainButton, false).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(buttonGroups) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex divide-x divider_secondary\"><div class=\"w-[0.15rem]\"></div><div class=\"w-[0.2rem]\"></div></div><div class=\"inline-flex justify-center items-center rounded-lg px-2 py-1 bodytext button_hover_primary\" _=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("on click or keyup[key is 'Enter'] toggle between .hidden and .absolute on #menu_" + mainButton.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/components/menuEdit.templ`, Line: 58, Col: 108}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" tabindex=\"0\"><span class=\"sr-only\">Menu</span> <span class=\"material-icons\">more_vert</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(buttonGroups) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("menu_" + mainButton.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/components/menuEdit.templ`, Line: 68, Col: 33}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"end-0 z-10 mt-2 w-56 divide-y divider_secondary rounded-lg background_primary border border_secondary shadow-lg hidden\" role=\"menu\" _=\"on keyup[key is 'Escape'] from the body add .hidden\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, buttonGroup := range buttonGroups {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"grid gap-1 p-2\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, button := range buttonGroup {
					templ_7745c5c3_Err = InnerButton(button, true).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func onClickHandler(hxTrigger string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_onClickHandler_64a6`,
		Function: `function __templ_onClickHandler_64a6(hxTrigger){console.log(hxTrigger)
	var reloadingDivs = document.querySelectorAll('div[id^='+hxTrigger+']');
	console.log(reloadingDivs)
	for (const reloadingDiv of reloadingDivs) {
		console.log(reloadingDiv.id)
		htmx.trigger('div[id='+reloadingDiv.id+']', hxTrigger)
	}
}`,
		Call:       templ.SafeScript(`__templ_onClickHandler_64a6`, hxTrigger),
		CallInline: templ.SafeScriptInline(`__templ_onClickHandler_64a6`, hxTrigger),
	}
}

var _ = templruntime.GeneratedTemplate
